spring:
  profiles:
    group:
      local: "local, key"
      dev: "develop, datasource, key"
      prod: "production, datasource, key"
    active: dev

  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
